In [2]:
import torch
torch.__version__

'2.0.0'

In [3]:
#scaler
scaler=torch.tensor(29)
scaler

tensor(29)

In [4]:
scaler.ndim

0

In [5]:
# get the python number within a tensor (only works one-element tensor)
scaler.item()

29

In [6]:
#vector
vector=torch.tensor([29,29])
vector

tensor([29, 29])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# matrix
MATRIX=torch.tensor([[29,12],[2,7]])
MATRIX

tensor([[29, 12],
        [ 2,  7]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
#tensor
TENSOR=torch.tensor([[12,8],[29,12],[2,7],[29,10]])
TENSOR

tensor([[12,  8],
        [29, 12],
        [ 2,  7],
        [29, 10]])

In [13]:
TENSOR.ndim

2

In [14]:
TENSOR.shape

torch.Size([4, 2])

In [15]:
#create random tensor of size(3,4)
random_tenosr=torch.rand(size=(3,4))
random_tenosr,random_tenosr.dtype

(tensor([[0.4830, 0.3151, 0.6337, 0.2719],
         [0.8127, 0.9441, 0.3967, 0.1199],
         [0.2718, 0.2870, 0.3965, 0.5160]]),
 torch.float32)

In [16]:
#create random tensor of size(224,224,3)
random_image_size_tenosr=torch.rand(size=(224,224,3))
random_image_size_tenosr.ndim,random_image_size_tenosr.shape

(3, torch.Size([224, 224, 3]))

In [17]:
#create a tensor ofall zeros 
zeros=torch.zeros(size=(3,3,4))
zeros,zeros.dtype

(tensor([[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]),
 torch.float32)

In [18]:
#create a tensor ofall zeros 
zeros=torch.ones(size=(3,3,4))
zeros,zeros.dtype

(tensor([[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]),
 torch.float32)

In [19]:
# use torch.arange(), torch.range() is deprecated
zero_to_ten_deprecated=torch.range(0,10)

#create a range of values 0 to 10
zero_to_ten=torch.arange(0,10,1)
zero_to_ten

/tmp/ipykernel_26/1627995601.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated=torch.range(0,10)


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
# can also create a tensor of zero similar to another tensor
ten_zeros=torch.zeros_like(input=zero_to_ten) # will have same shape
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [21]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None, # defaults to None, which is torch.float32 or whatever datatypr=e is passed
                             device=None, # defaults to None, which uses the defult tensor type
                             requires_grad=False # if True, operations performed i=on the tensor are recorded  
                            )
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [22]:
float_16_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=torch.float16, # torch.half also works
                            )
float_16_tensor.dtype

torch.float16

In [23]:
#create a tensor
tensor=torch.rand(3,4)

# find out details about it 
print(tensor)
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

tensor([[0.4378, 0.6975, 0.2269, 0.8256],
        [0.8877, 0.6296, 0.1263, 0.4187],
        [0.6073, 0.7336, 0.9502, 0.2822]])
torch.Size([3, 4])
torch.float32
cpu


In [24]:
# craete tensor of values and add a number to it
tensor=torch.tensor([1,2,3])
tensor+100

tensor([101, 102, 103])

In [25]:
tensor*100

tensor([100, 200, 300])

In [26]:
tensor=tensor-10
tensor

tensor([-9, -8, -7])

In [27]:
tensor=tensor+10
tensor

tensor([1, 2, 3])

In [28]:
torch.multiply(tensor,11)

tensor([11, 22, 33])

In [29]:
# element wise multiplication
tensor*tensor

tensor([1, 4, 9])

In [30]:
import torch
tensor=torch.tensor([1,2,3])
tensor.shape

torch.Size([3])

In [31]:
torch.matmul(tensor,tensor)

tensor(14)

In [32]:
tensor@tensor

tensor(14)

In [33]:
%%time
value=0
for i in range(len(tensor)):
    value=+ tensor[i]*tensor[i]
value

CPU times: user 177 µs, sys: 42 µs, total: 219 µs
Wall time: 279 µs


tensor(9)

In [34]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 45 µs, sys: 10 µs, total: 55 µs
Wall time: 151 µs


tensor(14)

In [35]:
# shapes need to be in right way
tensor_a=torch.tensor([[1,2],[3,4],[5,6]],dtype=torch.float32)
tensor_b=torch.tensor([[11,22],[33,44],[55,66]],dtype=torch.float32)

torch.matmul(tensor_a,tensor_b)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [36]:
print(tensor_a.shape)
print(tensor_b.shape)

torch.Size([3, 2])
torch.Size([3, 2])


In [37]:
print(tensor_a)
print(tensor_b.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[11., 33., 55.],
        [22., 44., 66.]])


In [38]:
torch.mm(tensor_a,tensor_b.T)

tensor([[ 55., 121., 187.],
        [121., 275., 429.],
        [187., 429., 671.]])

In [39]:
# since the linear layer starts with a random weights amtrix, let's make it reproducible
torch.manual_seed(42)

# this use matrix multiplication
linear=torch.nn.Linear(in_features=2, # in_features matches dimensions of input feature
                      out_features=6 # out_features describe outer value
                      )
x=tensor_a
output=linear(x)
print(x.shape)
print(output)
print(output.shape)

torch.Size([3, 2])
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)
torch.Size([3, 6])


In [40]:
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [41]:
print(x.max())
print(x.min())
print(x.type(torch.float32).mean()) # won't work without flaot datatype
print(x.sum())

tensor(90)
tensor(0)
tensor(45.)
tensor(450)


In [42]:
print(torch.max(x))
print(torch.min(x))
print(torch.mean(x.type(torch.float32)))
print(torch.sum(x))

tensor(90)
tensor(0)
tensor(45.)
tensor(450)


In [43]:
print(x)

print(torch.argmax(x))
print(torch.argmin(x))

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
tensor(9)
tensor(0)


In [44]:
# crate a tensor and check it's type
tensor=torch.arange(10.,30.,2.)
tensor.dtype

torch.float32

In [45]:
tensor_float16=tensor.type(torch.float16)
tensor_float16

tensor([10., 12., 14., 16., 18., 20., 22., 24., 26., 28.], dtype=torch.float16)

In [46]:
tensor_int8=tensor.type(torch.int8)
tensor_int8

tensor([10, 12, 14, 16, 18, 20, 22, 24, 26, 28], dtype=torch.int8)

In [47]:
x=torch.arange(1.,8.)
(x,x.shape)

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [48]:
x_reshaped=x.reshape(1,7)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [49]:
z=x.view(1,7)
z.shape,z

(torch.Size([1, 7]), tensor([[1., 2., 3., 4., 5., 6., 7.]]))

In [50]:
#changing z changes x
z[:,1]=100
z,x

(tensor([[  1., 100.,   3.,   4.,   5.,   6.,   7.]]),
 tensor([  1., 100.,   3.,   4.,   5.,   6.,   7.]))

In [51]:
#stack tensors on top of each other
x_stacked=torch.stack([x,x,x,x,x],dim=1)
x_stacked

tensor([[  1.,   1.,   1.,   1.,   1.],
        [100., 100., 100., 100., 100.],
        [  3.,   3.,   3.,   3.,   3.],
        [  4.,   4.,   4.,   4.,   4.],
        [  5.,   5.,   5.,   5.,   5.],
        [  6.,   6.,   6.,   6.,   6.],
        [  7.,   7.,   7.,   7.,   7.]])

In [52]:
print(x_reshaped)
print(x_reshaped.shape)

# remove extra dimension from x_reshaped
x_squeezed=x_reshaped.squeeze()

print(x_squeezed)
print(x_squeezed.shape)

tensor([[  1., 100.,   3.,   4.,   5.,   6.,   7.]])
torch.Size([1, 7])
tensor([  1., 100.,   3.,   4.,   5.,   6.,   7.])
torch.Size([7])


In [53]:
# crate tensor with specific shape
x_original=torch.rand(224,224,3)

# permute the orignal tensor to rearrange the axis order
x_permuted=x_original.permute(2,0,1)  # shifts axis 0->1, 1->2, 2->0

print(x_original.shape)
print(x_permuted.shape)


torch.Size([224, 224, 3])
torch.Size([3, 224, 224])


In [54]:
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [55]:
print(x[0])
print(x[0][0])
print(x[0][0][0])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3])
tensor(1)


In [56]:
# get all values of 0th dimension and the 0 index of 1st dimension
x[:,0]

tensor([[1, 2, 3]])

In [57]:
# get all values of 0th and 1st dimension but only 1 index of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [58]:
# get all values of 0th dimension but only 1 index value of 1st dimension and 2nd dimension
x[:,1,1]

tensor([5])

In [59]:
# get all values of 2nd dimension but only 0 index value of 0th dimension and 1st dimension
x[0,0,:]

tensor([1, 2, 3])

In [60]:
import numpy as np
arr=np.arange(1.0,8.0)
tensor=torch.from_numpy(arr)
tensor,arr

(tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 array([1., 2., 3., 4., 5., 6., 7.]))

In [61]:
arr=arr+1
tensor,arr

(tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 array([2., 3., 4., 5., 6., 7., 8.]))

In [62]:
# tensor to numpy array
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [63]:
tensor=tensor+1
tensor,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [64]:
random_tensor_1=torch.rand(3,4)
random_tensor_2=torch.rand(3,4)

print(random_tensor_1)
print(random_tensor_2)

random_tensor_1==random_tensor_2

tensor([[0.8016, 0.3649, 0.6286, 0.9663],
        [0.7687, 0.4566, 0.5745, 0.9200],
        [0.3230, 0.8613, 0.0919, 0.3102]])
tensor([[0.9536, 0.6002, 0.0351, 0.6826],
        [0.3743, 0.5220, 0.1336, 0.9666],
        [0.9754, 0.8474, 0.8988, 0.1105]])


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [65]:
# set the random seed
RANDOM_SEED=4
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_3=torch.rand(3,4)

# have to reset the seed value every time a new rand() is called
# without this, tensor_4 would be differnt to tensor_3
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_4=torch.rand(3,4)

print(random_tensor_3)
print(random_tensor_4)

random_tensor_3==random_tensor_4

tensor([[0.5596, 0.5591, 0.0915, 0.2100],
        [0.0072, 0.0390, 0.9929, 0.9131],
        [0.6186, 0.9744, 0.3189, 0.2148]])
tensor([[0.5596, 0.5591, 0.0915, 0.2100],
        [0.0072, 0.0390, 0.9929, 0.9131],
        [0.6186, 0.9744, 0.3189, 0.2148]])


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [66]:
# check for GPU
torch.cuda.is_available()

True

In [67]:
device="cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [68]:
# count the number of devices
torch.cuda.device_count()

2

In [70]:
# create tensor (default on CPU)
tensor=torch.tensor([1,2,3])

# tensor not on GPU
print(tensor,tensor.device)

# move tensor to GPU (if available)
tensor_on_gpu=tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

In [71]:
#if tensor is on GPU, can't transform it to numpy (this will error)
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [73]:
tensor_back_on_cpu=tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [74]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## Exercise

### 1] Documentation reading - A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness). See the documentation on torch.Tensor and for torch.cuda.

### 2] Create a random tensor with shape (7, 7).

In [1]:
import torch
tensor=torch.rand(7,7)
tensor

tensor([[0.1561, 0.9946, 0.4427, 0.5764, 0.0239, 0.3450, 0.2515],
        [0.1225, 0.6944, 0.8015, 0.9216, 0.2013, 0.6328, 0.0049],
        [0.8009, 0.1935, 0.9613, 0.4451, 0.8157, 0.5332, 0.8023],
        [0.1972, 0.7478, 0.0945, 0.5718, 0.6857, 0.1196, 0.6589],
        [0.0159, 0.1484, 0.1355, 0.7563, 0.0626, 0.1201, 0.9267],
        [0.1329, 0.4396, 0.5563, 0.3175, 0.8515, 0.6775, 0.6570],
        [0.0434, 0.5491, 0.0960, 0.1342, 0.7798, 0.7061, 0.2752]])

### 3] Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [8]:
tensor_1=torch.rand(1,7)
res=torch.matmul(tensor,tensor_1.T)
res

tensor([[1.1173],
        [1.7231],
        [1.4061],
        [1.9499],
        [0.9564],
        [1.3146],
        [1.1037]])

### 4] Set the random seed to 0 and do exercises 2 & 3 over again.

In [10]:
RANDOM_SEED=0
torch.manual_seed(RANDOM_SEED)
tensor=torch.rand(7,7)

torch.manual_seed(RANDOM_SEED)
tesnor_1=torch.rand(1,7)

res=torch.mm(tensor,tensor_1.T)
res

tensor([[1.1173],
        [1.7231],
        [1.4061],
        [1.9499],
        [0.9564],
        [1.3146],
        [1.1037]])

### 5] Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.

In [12]:
RANDOM_SEED=1234
torch.cuda.manual_seed(RANDOM_SEED)
tensor=torch.rand(7,7)

torch.cuda.manual_seed(RANDOM_SEED)
tesnor_1=torch.rand(1,7)

res=torch.mm(tensor,tensor_1.T)
res

tensor([[1.8249],
        [1.5044],
        [0.8366],
        [1.4783],
        [1.6913],
        [1.2264],
        [1.1057]])

### 6] Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

In [13]:
device="cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [17]:
torch.manual_seed(1234)

tensor_on_cpu=torch.rand(2,3)
tensor_on_gpu=tensor_on_cpu.to(device)

tensor_on_cpu_1=torch.rand(2,3)
tensor_on_gpu_1=tensor_on_cpu_1.to(device)

print(tensor_on_gpu.device)
print(tensor_on_gpu_1.device)

cuda:0
cuda:0


### 7] Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [18]:
tensor_on_gpu.shape,tensor_on_gpu_1.shape

(torch.Size([2, 3]), torch.Size([2, 3]))

In [21]:
MAT=torch.mm(tensor_on_gpu.T,tensor_on_gpu_1)
MAT

tensor([[0.1230, 0.3009, 0.2260],
        [0.0401, 0.2338, 0.3036],
        [0.2457, 0.6707, 0.5696]], device='cuda:0')

### 8] Find the maximum and minimum values of the output of 7.

In [24]:
print(MAT.max())
print(torch.min(MAT))

tensor(0.6707, device='cuda:0')
tensor(0.0401, device='cuda:0')


### 9] Find the maximum and minimum index values of the output of 7.

In [25]:
print(torch.argmax(MAT))
print(MAT.argmin())

tensor(7, device='cuda:0')
tensor(3, device='cuda:0')


### 10] Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [27]:
torch.manual_seed(7)
tensor_a=torch.rand(1,1,1,10)
tensor_b=tensor_a.squeeze()
print(tensor_a,tensor_a.shape)
print(tensor_b,tensor_b.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
